config/routes.rb
Rails.application.routes.draw do
  resources :trains
  resources :passengers
  resources :reviews
  resources :tickets
  resources :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'passenger_show_route', to: 'admins#passenger_show', as: 'passenger_show_route'
  get 'train_show_route', to: 'admins#train_show', as: 'train_show_route'
  get 'ticket_show_route', to: 'admins#ticket_show', as: 'ticket_show_route'
  get 'review_show_route', to: 'admins#review_show', as: 'review_show_route'
  
  get 'trainstation_filter_route', to: "trains#trainstation_filter", as: "trainstation_filter_route"
  get 'filter_by_rating', to:"trains#filter_by_rating", as: 'filter_by_rating'
  get 'search_passenger_by_train_number', to:"passengers#search_passenger_by_train_number", as: 'search_passenger_by_train_number'
  get 'search_review_by_train_number', to:"reviews#search_review_by_train_number", as: 'search_review_by_train_number'
  get 'search_review_by_passenger_name', to:"reviews#search_review_by_passenger_name", as: 'search_review_by_passenger_name'
  get 'pbooking_route', to: 'passengers#pbooking', as: 'pbooking_route'
  get 'booking_show_route', to: 'passengers#booking_show', as: 'booking_show_route'
  get 'ptrain_show_route', to: 'passengers#ptrain_show', as: 'ptrain_show_route'
  get 'pshow_reviews_route', to: 'reviews#pshow_reviews', as: 'pshow_reviews_route'
  get 'newtrain', to: "trains#new", as: 'newtrain'
  get 'newticket', to: "tickets#new", as: 'newticket'
  get 'newreview', to: "reviews#new", as: 'newreview'

  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: "passengers#new", as: 'signup'
  get 'alogin', to: "sessions#anew", as: 'alogin'
  get 'plogin', to: "sessions#pnew", as: 'plogin'
  get 'logout', to: "sessions#destroy", as: 'logout'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/admins/_admin.html.erb
<div id="<%= dom_id admin %>">
  <p>
    <strong>Username:</strong>
    <%= admin.username %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= admin.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= admin.email %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= admin.password %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= admin.phone %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= admin.address %>
  </p>

  <p>
    <strong>Credit number:</strong>
    <%= admin.credit_number %>
  </p>

</div>

app/views/admins/_form.html.erb
<%= form_with(model: @admin, local: true) do |form| %>
  <% if admin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
        <% admin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    Username: <%=@admin.username%>
  </div>
<br>
  <div>
    Name: <%=@admin.name%>

  </div>
<br>
  <div>
    Email: <%=@admin.email%>

  </div>
<br>
  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :credit_number, style: "display: block" %>
    <%= form.text_field :credit_number %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render "form", admin: @admin %>

<br>

<div>
  <%= link_to "Back to admins", admins_path %>
</div>

app/views/admins/index.html.erb
<p style="color: green"><%= notice %></p>

<% admin_user = Admin.find(session[:admin_id]) %>
<h1>Admins Dashboard</h1>

  <td><%= link_to 'Edit profile', edit_admin_path(admin_user) %></td>

  <br><%= link_to "Show Passengers", passenger_show_route_path %>
  <br><%= link_to "Show Trains", train_show_route_path %> 
  <br><%= link_to "Show Tickets", ticket_show_route_path %>
  <br><%= link_to "Show Reviews", review_show_route_path %>
<br >
<br><td>List Passengers by train number</td>
<%= form_tag(search_passenger_by_train_number_path, :method => "get") do %>
  <div class="input-group">
    <%= search_field_tag :train_number, params[:train_number], placeholder: "Enter Train Number", class: "form-control" %>
    <div class="input-group-btn">
      <%= button_tag "Search", :class =>'btn btn-info glyphicon glyphicon-search', :auth_name => nil %>
    </div>
  </div>
<% end %>  
 
<br>
<%= link_to 'Logout', logout_path %>

app/views/admins/new.html.erb
<h1>New admin</h1>

<%= render "form", admin: @admin %>

<br>

<div>
  <%= link_to "Back to admins", admins_path %>
</div>

app/views/admins/passenger_show.html.erb
<%= stylesheet_link_tag 'application' %>
<table class="table_class">  
<tr>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Address</th>
    <th>Credit card</th>
  </tr>

<% Passenger.all.each do |passenger| %>
  <tr>
    <td><%= passenger.name %></td>
    <td><%= passenger.email %></td>
    <td><%= passenger.phone %></td>
    <td><%= passenger.address %></td>
    <td><%= passenger.credit_card %></td>
    <td><%= link_to 'Show', passenger %></td>
    <td><%= link_to 'Edit', edit_passenger_path(passenger) %></td>
    <td><%= button_to 'Destroy', passenger, method: :delete, data: { confirm: 'Are you sure?' }%></td>
  </tr>
<% end %>
</table>
<br>
<%= link_to "Add Passenger", signup_path %> <br>
<%= link_to 'Back to dashboard', admins_path %>

app/views/admins/review_show.html.erb
<%= stylesheet_link_tag 'application' %>
<table class="table_class">  
<tr>
    <th>Rating</th>
    <th>Feedback</th>
    <th>Review By</th>
    <th>Train Number</th>
  </tr>

<% Review.all.each do |review| %>
  <tr>
    <td><%= review.rating %></td>
    <td><%= review.feedback %></td>
    <%if review.passenger_id == 1 && @result == "Admin"%>
    <td><%= Admin.find_by(id: session[:admin_id]).name %></td>
    <%else%>
    <td><%= Passenger.find(review.passenger_id).name %></td>
    <%end%>
    <td><%= Train.find(review.train_id).train_number %></td>
    <td><%= link_to 'Show', review %></td>
    <th> <%= link_to "Edit", edit_review_path(review, :train_id => review.train_id) %></th>
    <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<br>
<br>
<%= form_tag(search_review_by_train_number_path, :method => "get") do %>
  <div class="input-group">
    <%= search_field_tag :train_number, params[:train_number], placeholder: "Enter Train Number", class: "form-control" %>
    <div class="input-group-btn">
      <%= button_tag "Search", :class =>'btn btn-info glyphicon glyphicon-search', :auth_name => nil %>
    </div>
  </div>
<% end %>
<br>
<br>
<%= form_tag(search_review_by_passenger_name_path, :method => "get") do %>
  <div class="input-group">
    <%= search_field_tag :passenger_name, params[:passenger_name], placeholder: "Enter Passenger Name", class: "form-control" %>
    <div class="input-group-btn">
      <%= button_tag "Search", :class =>'btn btn-info glyphicon glyphicon-search', :auth_name => nil %>
    </div>
  </div>
<% end %>



<%= link_to 'Back to dashboard', admins_path %>

app/views/admins/show.html.erb
<p style="color: green"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @passengers.name %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |


<%= link_to "Back to admins", admins_path %>

  
</div>

app/views/admins/ticket_show.html.erb
<%= stylesheet_link_tag 'application' %>
<table class="table_class">  
  <tr>
    <th>Passenger Name</th>
    <th>Train Number</th>
    <th>Confirmation Number</th>
    <th>Booked By</th>
    <th>Booked on</th>
  </tr>

<% Ticket.all.each do |ticket| %>
  <tr>
  <td><%= Passenger.find_by(id: ticket.passenger_id).name %></td>
  <td><%= Train.find_by(id: ticket.train_id).train_number %></td> 
  <td><%= ticket.confirmation_number %></td>
  <% if ticket.booked_by == "admin" %>
  <td><%= Admin.find_by(id: session[:admin_id]).name %></td>
  <%else%>
  <td><%= Passenger.find_by(id: ticket.booked_by.to_i).name %></td>
  <%end%>
  <td><%= ticket.created_at %></td>
    <td><%= button_to "Destroy", Ticket.find_by(passenger_id: ticket.passenger_id, train_id:ticket.train_id), method: :delete %></td>
  </tr>
<% end %>
</table>
<br>
<%= link_to 'Back to dashboard', admins_path %>

app/views/admins/train_show.html.erb
<%= stylesheet_link_tag 'application' %>
<table class="table_class">
  <tr>
    <th>Train number</th>
    <th>Departure station</th>
    <th>Termination station</th>
    <th>Departure date</th>
    <th>Departure time</th>
    <th>Arrival date</th>
    <th>Arrival time</th>
    <th>Ticket price</th>
    <th>Train capacity</th>
    <th>Seats left</th>
    <th>Average Rating</th>

  </tr>

<% Train.all.each do |train| %>
  <tr>
    <td><%= train.train_number %></td>
    <td><%= train.departure_station %></td>
    <td><%= train.termination_station %></td>
    <td><%= train.departure_date %></td>
    <td><%= train.departure_time.strftime("%H:%M") %></td>
    <td><%= train.arrival_date %></td>
    <td><%= train.arrival_time.strftime("%H:%M") %></td>
    <td><%= train.ticket_price %></td>
    <td><%= train.train_capacity %></td>
    <td><%= train.seats_left %></td>
    <%review = Review.where(:train_id => train.id)%>
    <td><%= review.average(:rating).to_i %></td>

    <td><%= link_to 'Book train', newticket_path(:train_id => train.id) %></td>
    <td>  <%= link_to "Add reviews", newreview_path(:train_id => train.id) %></td>
    <td><%= link_to 'Show', train %></td>
    <td><%= link_to 'Edit', edit_train_path(train) %></td>
    <td><%= link_to 'Destroy', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  
    </tr>
<% end %>
</table>
<br>
<table>
<tr>
<td>
<%= form_tag(trainstation_filter_route_path, :method => "get") do %>
  <div class="input-group">
    <%= search_field_tag :departure_station, params[:departure_station], placeholder: "Enter Departure Station", class: "form-control" %>
    <%= search_field_tag :termination_station, params[:termination_station], placeholder: "Enter Termination Station", class: "form-control" %>
    <div class="input-group-btn">
      <%= button_tag "Search", :class =>'btn btn-info glyphicon glyphicon-search', :auth_name => nil %>
    </div>
  </div>
<% end %>
</td>

</tr>
</table>
<br>

<%= link_to 'Add train', newtrain_path %>
<br><%= link_to 'Back to dashboard', admins_path %>