config/routes.rb
Rails.application.routes.draw do
  resources :trains
  resources :passengers
  resources :reviews
  resources :tickets
  resources :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'passenger_show_route', to: 'admins#passenger_show', as: 'passenger_show_route'
  get 'train_show_route', to: 'admins#train_show', as: 'train_show_route'
  get 'ticket_show_route', to: 'admins#ticket_show', as: 'ticket_show_route'
  get 'review_show_route', to: 'admins#review_show', as: 'review_show_route'
  
  get 'trainstation_filter_route', to: "trains#trainstation_filter", as: "trainstation_filter_route"
  get 'filter_by_rating', to:"trains#filter_by_rating", as: 'filter_by_rating'
  get 'search_passenger_by_train_number', to:"passengers#search_passenger_by_train_number", as: 'search_passenger_by_train_number'
  get 'search_review_by_train_number', to:"reviews#search_review_by_train_number", as: 'search_review_by_train_number'
  get 'search_review_by_passenger_name', to:"reviews#search_review_by_passenger_name", as: 'search_review_by_passenger_name'
  get 'pbooking_route', to: 'passengers#pbooking', as: 'pbooking_route'
  get 'booking_show_route', to: 'passengers#booking_show', as: 'booking_show_route'
  get 'ptrain_show_route', to: 'passengers#ptrain_show', as: 'ptrain_show_route'
  get 'pshow_reviews_route', to: 'reviews#pshow_reviews', as: 'pshow_reviews_route'
  get 'newtrain', to: "trains#new", as: 'newtrain'
  get 'newticket', to: "tickets#new", as: 'newticket'
  get 'newreview', to: "reviews#new", as: 'newreview'

  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: "passengers#new", as: 'signup'
  get 'alogin', to: "sessions#anew", as: 'alogin'
  get 'plogin', to: "sessions#pnew", as: 'plogin'
  get 'logout', to: "sessions#destroy", as: 'logout'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ticket.rb
class Ticket < ApplicationRecord
    belongs_to :admin
    belongs_to :train
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update destroy ]
  # GET /tickets or /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1 or /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
    if @train.nil?
      @train = Train.find(params[:train_id])
    end
  end
  # GET /tickets/1/edit
  def edit
    if @train.nil?
      @train = Train.find(params[:train_id])
    end
  end

  # POST /tickets or /tickets.json
  def create   
    p = params["ticket"][:non_model_ticket_cnt] 
    if session[:passenger_id] != nil
      pid = Passenger.find(session[:passenger_id]).id
    else
      pid = "admin"
    end
    p.to_i.times do
      @ticket = Ticket.new(ticket_params)
      @ticket.booked_by = pid
      @ticket.confirmation_number = Array.new(10){[*"A".."Z", *"0".."9"].sample}.join
      @train = Train.find_by(id: @ticket[:train_id])
      @train.seats_left = @train.seats_left - 1
      @train.save
      @ticket.save
    end
      respond_to do |format|
        if @ticket.save
          format.html { redirect_to ticket_url(@ticket), notice: "Ticket was booked successfully." }
          format.json { render ticket_url(@ticket), status: :created, location: @ticket }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @ticket.errors, status: :unprocessable_entity }
        end
      end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully updated." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @train = Train.find_by(id: @ticket[:train_id])
    @train.seats_left = @train.seats_left + 1
    @train.save
    if Review.find_by(train_id: @train[:id])
      Review.where(:train_id => @train[:id]).destroy_all
    end
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url, notice: "Ticket was successfully cancelled." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    #Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:train_id, :passenger_id)   
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_with(model: @ticket) do |form| %>
  <% if @ticket.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>
      <ul>
        <% @ticket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :non_model_ticket_cnt, "Ticket Count", style: "display: block" %>
    <%= form.select :non_model_ticket_cnt, options_for_select((1..@train.seats_left).map { |count| [count, count] }) %>
    <p>Total Price: <span id="displaySelectedTicketCount">None</span></p>  
  </div>

  <div>
    <%= form.label :passenger_id, "Book for", style: "display: block" %>
    <%= form.select :passenger_id, options_for_select((Passenger.all.drop(1)).map { |passenger| [passenger.name, passenger.id] }) %>
  </div>
  
  <div class="field">
    <%= form.hidden_field :train_id, value: @train.id %>
    <%= form.hidden_field :ticket_price, value: @train.ticket_price %>
  </div>
<br>
  <div class="actions">
    <%= form.submit 'Book Ticket' %>
  </div>

  <script>
  const selectField = document.querySelector('select[name="ticket[non_model_ticket_cnt]"]') ; 
  const displaySelectedTicketCount = document.getElementById('displaySelectedTicketCount');
  const ticketPrice = parseFloat(document.querySelector('input[name="ticket[ticket_price]"]').value);
  selectField.addEventListener('change', function () {
    const selectedCount = selectField.value;

    if (!isNaN(selectedCount)) {
      const result = selectedCount * ticketPrice;

      displaySelectedTicketCount.textContent = result;
    } else {
      displaySelectedTicketCount.textContent = 'Invalid input';
    }
    
  
  });
</script>
<% end %>

app/views/tickets/_ticket.html.erb
<div id="<%= dom_id ticket %>">
  <p>
    <strong>Confirmation number:</strong>
    <%= ticket.confirmation_number %>
  </p>

</div>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<br>

<div>
  <%= link_to "Show this ticket", @ticket %> |
  <%= link_to "Back to tickets", tickets_path %>
</div>

app/views/tickets/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="tickets">
  
    <p>
    <% if session[:passenger_id] != nil %>
    <%= link_to "Back to tickets", pbooking_route_path %>
    <%else%>
    <th><%= link_to 'Back to tickets', ticket_show_route_path %></th>
    <%end%>
    </p>
 
</div>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>


<%= render 'form', ticket: @ticket %>
<br>
<% if session[:passenger_id] != nil %>
    <td><%= link_to 'Back to trains', ptrain_show_route_path %></td>
    <%else%>
    <th><%= link_to 'Back to trains', train_show_route_path %></th>
    <%end%>

app/views/tickets/show.html.erb
<p style="color: green"><%= notice %></p>


<div>
<% if session[:passenger_id] != nil %>
<%= link_to "Back to trains", ptrain_show_route_path %>
<%else%>
<th><%= link_to 'Back to tickets', ticket_show_route_path %></th>
<%end%>


</div>