config/routes.rb
Rails.application.routes.draw do
  resources :trains
  resources :passengers
  resources :reviews
  resources :tickets
  resources :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'passenger_show_route', to: 'admins#passenger_show', as: 'passenger_show_route'
  get 'train_show_route', to: 'admins#train_show', as: 'train_show_route'
  get 'ticket_show_route', to: 'admins#ticket_show', as: 'ticket_show_route'
  get 'review_show_route', to: 'admins#review_show', as: 'review_show_route'
  
  get 'trainstation_filter_route', to: "trains#trainstation_filter", as: "trainstation_filter_route"
  get 'filter_by_rating', to:"trains#filter_by_rating", as: 'filter_by_rating'
  get 'search_passenger_by_train_number', to:"passengers#search_passenger_by_train_number", as: 'search_passenger_by_train_number'
  get 'search_review_by_train_number', to:"reviews#search_review_by_train_number", as: 'search_review_by_train_number'
  get 'search_review_by_passenger_name', to:"reviews#search_review_by_passenger_name", as: 'search_review_by_passenger_name'
  get 'pbooking_route', to: 'passengers#pbooking', as: 'pbooking_route'
  get 'booking_show_route', to: 'passengers#booking_show', as: 'booking_show_route'
  get 'ptrain_show_route', to: 'passengers#ptrain_show', as: 'ptrain_show_route'
  get 'pshow_reviews_route', to: 'reviews#pshow_reviews', as: 'pshow_reviews_route'
  get 'newtrain', to: "trains#new", as: 'newtrain'
  get 'newticket', to: "tickets#new", as: 'newticket'
  get 'newreview', to: "reviews#new", as: 'newreview'

  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: "passengers#new", as: 'signup'
  get 'alogin', to: "sessions#anew", as: 'alogin'
  get 'plogin', to: "sessions#pnew", as: 'plogin'
  get 'logout', to: "sessions#destroy", as: 'logout'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/passenger.rb
class Passenger < ApplicationRecord
    validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP },unless: -> { email.blank? }
    validates :phone, format: { with: /\A\d{10}\z/, message: 'should be 10 digit' },unless: -> { phone.blank? }
    validates :credit_card, format: { with: /\A\d{16}\z/, message: 'should be 16 digit' },unless: -> { credit_card.blank? }
    validates :name, presence: true
    validates :password_digest, presence: true, allow_blank: true
    has_secure_password
    belongs_to :admin
    has_many :reviews
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  before_action :set_passenger, only: %i[ show edit update destroy ]
 
  # before_action :redirect_to_root, only: [:index]

  # GET /passengers or /passengers.json
  def index
    @passengers = Passenger.all
    @admins = Admin.all
  end

  # GET /passengers/1 or /passengers/1.json
  def show
    if @passenger.id == session[:passenger_id] || session[:admin_id] != nil
    
    else
      redirect_to root_path, error: "Not allowed to access this page"
    end
  end

  # GET /passengers/new
  def new
    @passenger = Passenger.new
  end

  # GET /passengers/1/edit
  def edit
  end

  # POST /passengers or /passengers.json
  def create
    @passenger = Passenger.new(passenger_params)

    respond_to do |format|
      if @passenger.save
        format.html { redirect_to passenger_url(@passenger), notice: "Passenger was successfully created." }
        format.json { render passenger_url(@passenger), status: :created, location: @passenger }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passengers/1 or /passengers/1.json
  def update
    respond_to do |format|
      if @passenger.update(passenger_params)
        format.html { redirect_to passenger_url(@passenger), notice: "Passenger was successfully updated." }
        format.json { render :show, status: :ok, location: @passenger }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passengers/1 or /passengers/1.json
  def destroy
    if Review.find_by(passenger_id: @passenger.id)
      Review.where(:passenger_id => @passenger.id).destroy_all
    end
    if @ticket = Ticket.find_by(passenger_id: @passenger.id)
      Ticket.where(:passenger_id => @passenger.id).destroy_all
    end
    @passenger.destroy
    session[:passenger_id] = nil
    if session[:admin_id] != nil
      respond_to do |format|
        format.html { redirect_to admins_path, notice: "Passenger was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to root_path, notice: "Passenger was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  
# Filter by train number for all reviews 
def search_passenger_by_train_number
  if params[:train_number].blank?
      redirect_to admins_path and return
  else
    @result_passenger = Array.new
    @train = Train.find_by(:train_number => params[:train_number])
    if @train == nil
      redirect_to admins_path and return
    end
    @tickets = Ticket.all
    @tickets.each do |ticket|
      if ticket.train_id == @train.id
        @result_passenger.append(ticket.passenger_id)
      end
    end
    end
    puts @result_passenger
  
end

  private
    def redirect_to_root
      redirect_to root_path
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_passenger
      @passenger = Passenger.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def passenger_params
      params.require(:passenger).permit(:name, :email, :password, :phone, :address, :credit_card)
    end
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/passengers/_form.html.erb
<%= form_with(model: passenger, local:true) do |form| %>
  <% if passenger.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(passenger.errors.count, "error") %> prohibited this passenger from being saved:</h2>

      <ul>
        <% passenger.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, required:true %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, required: true %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, required: true %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address, required: true %>
  </div>

  <div>
    <%= form.label :credit_card, style: "display: block" %>
    <%= form.text_field :credit_card, required: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/passengers/_passenger.html.erb
<div id="<%= dom_id passenger %>">
  <p>
    <strong>Name:</strong>
    <%= passenger.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= passenger.email %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= passenger.password %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= passenger.phone %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= passenger.address %>
  </p>

  <p>
    <strong>Credit card:</strong>
    <%= passenger.credit_card %>
  </p>

</div>

app/views/passengers/booking_show.html.erb
<%= stylesheet_link_tag 'application' %>
<table class="table_class">
  <tr>
    <th>Train number</th>
    <th>Departure station</th>
    <th>Termination station</th>
    <th>Departure date</th>
    <th>Departure time</th>
    <th>Arrival date</th>
    <th>Arrival time</th>
    <th>Ticket price</th>
    <th>Train capacity</th>
    <th>Seats left</th>

  </tr>
<% passenger_user = Passenger.find(session[:passenger_id]) %>

<% Train.all.each do |train| %>
  <% if Ticket.find_by(passenger_id: passenger_user.id, train_id:train.id) && train.departure_date<Date.today || (train.departure_date == Date.today && train.departure_time.strftime("%H:%M")<Time.now.strftime("%H:%M")) %>
    <tr>
      <td><%= train.train_number %></td>
      <td><%= train.departure_station %></td>
      <td><%= train.termination_station %></td>
      <td><%= train.departure_date %></td>
      <td><%= train.departure_time.strftime("%H:%M") %></td>
      <td><%= train.arrival_date %></td>
      <td><%= train.arrival_time.strftime("%H:%M") %></td>
      <td><%= train.ticket_price %></td>
      <td><%= train.train_capacity %></td>
      <td><%= train.seats_left %></td>
      <% @review = Review.find_by(passenger_id: passenger_user.id, train_id:train.id) %>
      <% if @review %>
        <th> <%= link_to "Edit your review", edit_review_path(@review, :train_id => train.id) %></th>
      <% else %>
        <td>  <%= link_to "Add reviews", newreview_path(:train_id => train.id) %></td>
      <% end %>  

    </tr>
  <% end %>
<% end %>
</table>

<%= link_to 'Back', passengers_path %>

app/views/passengers/edit.html.erb
<h1>Editing passenger</h1>

<%= render "form", passenger: @passenger %>

<br>

<div>
<% if session[:passenger_id] != nil %>
<%= link_to "Back to passengers", passengers_path %>
<%else%>
<th><%= link_to 'Back to passengers', passenger_show_route_path %></th>
<%end%>
</div>

app/views/passengers/index.html.erb
<p style="color: green"><%= notice %></p>
<% passenger_user = Passenger.find(session[:passenger_id]) %>
<h1>Welcome <%=passenger_user.name %> !</h1>

<table>
  <thead>
    <tr>
      Name: <%=passenger_user.name %>
      <br>Email: <%=passenger_user.email%>  
      <br>Address: <%=passenger_user.address%>
      <br>Phone: <%=passenger_user.phone%>
      
    </tr>
  </thead>

</table>
<br>
    <td><%= link_to 'Edit profile', edit_passenger_path(passenger_user) %></td>
    <br><td><%= link_to 'Delete profile', passenger_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <br>
    <br><%= link_to 'Show available trains', ptrain_show_route_path %></td>
    <br><%= link_to 'Show Travel history', booking_show_route_path %></td>
    <br><%= link_to 'Show my bookings', pbooking_route_path %></td>
    <br><%= link_to 'Show my reviews', pshow_reviews_route_path %></td>
<br>
<br><td><%= link_to 'Logout', logout_path %></td>

app/views/passengers/new.html.erb
<h1>New passenger</h1>

<%= render "form", passenger: @passenger %>

<br>

<div>
<% if session[:admin_id] == nil %>
  <%= link_to "Back", passengers_path %>
<% else %>
  <th><%= link_to 'Back to passengers', passenger_show_route_path %></th>
<%end%>
</div>

app/views/passengers/pbooking.html.erb
<%= stylesheet_link_tag 'application' %>
<table class="table_class">
  <tr>
  <th>Passenger Name</th>
  <th>Train Number</th>
  <th>Confirmation Number</th>
  <th>Booked By</th>
  <th>Booked on</th>  
 </tr>
 <% passenger_user = Passenger.find(session[:passenger_id]) %>

<% Ticket.all.each do |ticket| %>
  <% if ticket.passenger_id == passenger_user.id || ticket.booked_by == passenger_user.id%>  
    <tr>
    <td><%= Passenger.find_by(id: ticket.passenger_id).name %></td>
    <td><%= Train.find_by(id: ticket.train_id).train_number %></td> 
    <td><%= ticket.confirmation_number %></td>
    <% if ticket.booked_by == "admin" %>
    <td><%= Admin.find_by(id: 1).name %></td>
    <%else%>
    <td><%= Passenger.find_by(id: ticket.booked_by.to_i).name %></td>
    <%end%>    
    <td><%= ticket.created_at %></td>
    
    <td><%= button_to "Destroy", Ticket.find_by(passenger_id: ticket.passenger_id, train_id:ticket.train_id), method: :delete %></td>
    </tr>
  <% end %>
<% end %>
</table>

<%= link_to 'Back', passengers_path %>

app/views/passengers/ptrain_show.html.erb
<%= stylesheet_link_tag 'application' %>
<table class="table_class">
  <tr>
    <th>Train number</th>
    <th>Departure station</th>
    <th>Termination station</th>
    <th>Departure date</th>
    <th>Departure time</th>
    <th>Arrival date</th>
    <th>Arrival time</th>
    <th>Ticket price</th>
    <th>Train capacity</th>
    <th>Seats left</th>
    <th>Average Rating</th>
    <th>Show Reviews</th>


  </tr>
<% passenger_user = Passenger.find(session[:passenger_id]) %>

<% Train.all.each do |train| %>
  <% if train.seats_left > 0 && train.departure_date > Date.today || (train.departure_date == Date.today && train.departure_time.strftime("%H:%M") > Time.now.strftime("%H:%M"))%>
    <tr>
      <td><%= train.train_number %></td>
      <td><%= train.departure_station %></td>
      <td><%= train.termination_station %></td>
      <td><%= train.departure_date %></td>
      <td><%= train.departure_time.strftime("%H:%M") %></td>
      <td><%= train.arrival_date %></td>
      <td><%= train.arrival_time.strftime("%H:%M") %></td>
      <td><%= train.ticket_price %></td>
      <td><%= train.train_capacity %></td>
      <td><%= train.seats_left %></td>
      <%review = Review.where(:train_id => train.id)%>
      <td><%= review.average(:rating).to_i %></td>
      <td><%= link_to 'Train reviews', search_review_by_train_number_path(:train_number => train.train_number) %></td>
      <td><%= link_to 'Book train', newticket_path(:train_id => train.id) %></td>
    </tr>
  <% end %>
<% end %>
</table>
<br>
<%= form_tag(trainstation_filter_route_path, :method => "get") do %>
    <div class="input-group">
      <%= search_field_tag :departure_station, params[:departure_station], placeholder: "Enter Departure Station", class: "form-control" %>
      <%= search_field_tag :termination_station, params[:termination_station], placeholder: "Enter Termination Station", class: "form-control" %>
      <div class="input-group-btn">
        <%= button_tag "Search", :class =>'btn btn-info glyphicon glyphicon-search', :auth_name => nil %>
      </div>
    </div>
    <% end %>

    <br>

<%= form_tag(filter_by_rating_path, :method => "get") do %>
    <%= label_tag :min_rating %>
    <%= select_tag :min_rating, options_for_select([5, 4, 3, 2, 1].map { |n| [n, n] }, params[:min_rating]), include_blank: true %>
    <%= submit_tag "Filter by Rating" %>
  <% end %>
  <br>

<%= link_to 'Back', passengers_path %>

app/views/passengers/search_passenger_by_train_number.erb
    <%if session[:admin_id] != nil%>
      <h2>Passenger list who booked train <%=params[:train_number]%></h2>
      <%= stylesheet_link_tag 'application' %>
      <table class="table_class">  <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Credit card</th>
    </tr>

    <% @result_passenger.each do |pid| %>
      <td><% passenger = Passenger.find_by(:id => pid) %></td>
      <tr>
      <td><%= passenger.name %></td>
      <td><%= passenger.email %></td>
      <td><%= passenger.phone %></td>
      <td><%= passenger.address %></td>
      <td><%= passenger.credit_card %></td>
      <td><%= link_to 'Show', passenger %></td>
      <td><%= link_to 'Edit', edit_passenger_path(passenger) %></td>
      <td><%= link_to 'Destroy', passenger, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </table>
  <br><td>List Passengers by train number</td>
  <%= form_tag(search_passenger_by_train_number_path, :method => "get") do %>
    <div class="input-group">
      <%= search_field_tag :train_number, params[:train_number], placeholder: "Enter Passenger Name", class: "form-control" %>
      <div class="input-group-btn">
        <%= button_tag "Search", :class =>'btn btn-info glyphicon glyphicon-search', :auth_name => nil %>
      </div>
    </div>
  <% end %>
  <br>
  <%= link_to 'Back to dashboard', admins_path %>
  <%else%>
    <h3>Restricted access</h3>
    <%= link_to 'Back', root_path %>

  <%end%>

app/views/passengers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @passenger %>

<div>
  <%= link_to "Edit this passenger", edit_passenger_path(@passenger) %> 
  <% if session[:passenger_id] != nil %>
    <%= link_to "Back to passengers", passengers_path %>
  <%else%>
    <th><%= link_to 'Back to passengers', passenger_show_route_path %></th>
  <%end%>
  

  <%= button_to "Destroy this passenger", @passenger, method: :delete , data: { confirm: 'Are you sure you want to delete this passenger?' }, class: 'btn btn-danger' %>
</div>