config/routes.rb
Rails.application.routes.draw do
  resources :trains
  resources :passengers
  resources :reviews
  resources :tickets
  resources :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'passenger_show_route', to: 'admins#passenger_show', as: 'passenger_show_route'
  get 'train_show_route', to: 'admins#train_show', as: 'train_show_route'
  get 'ticket_show_route', to: 'admins#ticket_show', as: 'ticket_show_route'
  get 'review_show_route', to: 'admins#review_show', as: 'review_show_route'
  
  get 'trainstation_filter_route', to: "trains#trainstation_filter", as: "trainstation_filter_route"
  get 'filter_by_rating', to:"trains#filter_by_rating", as: 'filter_by_rating'
  get 'search_passenger_by_train_number', to:"passengers#search_passenger_by_train_number", as: 'search_passenger_by_train_number'
  get 'search_review_by_train_number', to:"reviews#search_review_by_train_number", as: 'search_review_by_train_number'
  get 'search_review_by_passenger_name', to:"reviews#search_review_by_passenger_name", as: 'search_review_by_passenger_name'
  get 'pbooking_route', to: 'passengers#pbooking', as: 'pbooking_route'
  get 'booking_show_route', to: 'passengers#booking_show', as: 'booking_show_route'
  get 'ptrain_show_route', to: 'passengers#ptrain_show', as: 'ptrain_show_route'
  get 'pshow_reviews_route', to: 'reviews#pshow_reviews', as: 'pshow_reviews_route'
  get 'newtrain', to: "trains#new", as: 'newtrain'
  get 'newticket', to: "tickets#new", as: 'newticket'
  get 'newreview', to: "reviews#new", as: 'newreview'

  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: "passengers#new", as: 'signup'
  get 'alogin', to: "sessions#anew", as: 'alogin'
  get 'plogin', to: "sessions#pnew", as: 'plogin'
  get 'logout', to: "sessions#destroy", as: 'logout'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ show edit update destroy ]

  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all
    @admins = Admin.all
  end

  # GET /reviews/1 or /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
    if @train.nil?
      @train = Train.find(params[:train_id])
    end
  end

  # GET /reviews/1/edit
  def edit
    if @train.nil?
      @train = Train.find(params[:train_id])
    end
    if @review.passenger_id == session[:passenger_id] || session[:admin_id] != nil

    else
      redirect_to root_path, error: "Not allowed to access this page"
    end
  end

  # POST /reviews or /reviews.json
  def create
    if session[:passenger_id] != nil
      pid = Passenger.find(session[:passenger_id]) 
    else
      pid = Admin.find(session[:admin_id])
    end
    puts pid.id
    @review = Review.new(review_params)
    @review.passenger_id = pid.id
    @train = Train.find_by(id: @review[:train_id])

    respond_to do |format|
      if @review.save
        format.html { redirect_to review_url(@review), notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to review_url(@review), notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url, notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

# Filter by train number for all reviews 
def search_review_by_train_number
  if params[:train_number].blank?
    if session[:passenger_id] != nil
      redirect_to passengers_path and return
    else
      redirect_to review_show_route_path and return
    end
  else
    @result_reviews = Array.new
    @reviews = Review.all
    @reviews.each do |review|
      @train = Train.find_by_id(review.train_id)
      if @train && @train.train_number == params[:train_number]
        @result_reviews.append(review)
      end
    end
    puts @result_reviews
  end
end

# Filter by train number for all reviews 
def search_review_by_passenger_name
  if params[:passenger_name].blank?
    if session[:passenger_id] != nil
      redirect_to passengers_path and return
    else
      redirect_to review_show_route_path and return
    end
  else
    @result_reviews_passenger = Array.new
    @reviews = Review.all
    @reviews.each do |review|
      @passenger = Passenger.find_by_id(review.passenger_id)
      if @passenger && @passenger.name == params[:passenger_name]
        @result_reviews_passenger.append(review)
      end
    end
    puts @result_reviews_passenger
  end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:rating, :feedback, :train_id)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_with(model: review) do |form| %>
  <% if review.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.select :rating, options_for_select([1, 2, 3, 4, 5]) %>
  </div>

  <div>
    <%= form.label :feedback, style: "display: block" %>
    <%= form.text_area :feedback %>
  </div>

  <div class="field">
    <%= form.hidden_field :train_id, value: @train.id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<div id="<%= dom_id review %>">
  <p>
    <strong>Rating:</strong>
    <%= review.rating %>
  </p>

  <p>
    <strong>Feedback:</strong>
    <%= review.feedback %>
  </p>

</div>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Show this review", @review %> |
  <%= link_to "Back to reviews", reviews_path %>
</div>

app/views/reviews/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="review">
  
    <p>
    <% if session[:passenger_id] != nil %>
    <%= link_to "Back to trains", booking_show_route_path %>
  <%else%>
    <th><%= link_to 'Back to reviews', review_show_route_path %></th>
  <%end%>
    </p>
 
</div>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render "form", review: @review %>

<br>

<div>
</div>
<% if session[:passenger_id] != nil %>
<%= link_to "Back to booking histroy", booking_show_route_path %>
<%else%>
    <th><%= link_to 'Back to trains', train_show_route_path %></th>
    <%end%>

app/views/reviews/pshow_reviews.erb
<%= stylesheet_link_tag 'application' %>
<table class="table_class">
  <tr>
    <th>Rating</th>
    <th>Feedback</th>
    <th>Review By</th>
    <th>Train ID</th>
  </tr>

<% Review.all.each do |review| %>
    <% if review.passenger_id == session[:passenger_id] %>  
  <tr>
    <td><%= review.rating %></td>
    <td><%= review.feedback %></td>
    <td><%= review.passenger_id %></td>
    <td><%= review.train_id %></td>
    <th> <%= link_to "Update", edit_review_path(review, :train_id => review.train_id) %></th>
  </tr>
  <%end%>
<% end %>
</table>
<%= link_to 'Back', passengers_path %>

app/views/reviews/search_review_by_passenger_name.erb
<%= stylesheet_link_tag 'application' %>
<table class="table_class">
  <tr>
    <th>Rating</th>
    <th>Feedback</th>
    <th>Review By</th>
    <th>Train Number</th>
  </tr>

<% @result_reviews_passenger.each do |review| %>
  <tr>
    <td><%= review.rating %></td>
    <td><%= review.feedback %></td>
    <td><%= Passenger.find(review.passenger_id).name %></td>
    <td><%= Train.find(review.train_id).train_number %></td>
    <td><%= link_to 'Show', review %></td>
    <th> <%= link_to "Edit", edit_review_path(review, :train_id => review.train_id) %></th>
    <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<br>
<br>

  <% if session[:passenger_id] != nil %>
  <%= form_tag(search_review_by_train_number_path, :method => "get") do %>
    <div class="input-group">
      <%= search_field_tag :train_number, params[:train_number], placeholder: "Enter Train Number", class: "form-control" %>
      <div class="input-group-btn">
        <%= button_tag "Search", :class =>'btn btn-info glyphicon glyphicon-search', :auth_name => nil %>
      </div>
    </div>
  <% end %>
  <br>
  <br>
  <%= form_tag(search_review_by_passenger_name_path, :method => "get") do %>
    <div class="input-group">
      <%= search_field_tag :passenger_name, params[:passenger_name], placeholder: "Enter Passenger Name", class: "form-control" %>
      <div class="input-group-btn">
        <%= button_tag "Search", :class =>'btn btn-info glyphicon glyphicon-search', :auth_name => nil %>
      </div>
    </div>
  <% end %>
    <%= link_to "Back to trains", ptrain_show_route_path %>
  <%else%>
    <th><%= link_to 'Back to reviews', review_show_route_path %></th>
  <%end%>
    

app/views/reviews/search_review_by_train_number.erb
<%= stylesheet_link_tag 'application' %>
<table class="table_class">
  <tr>
    <th>Rating</th>
    <th>Feedback</th>
    <th>Review By</th>
    <th>Train Number</th>
  </tr>
<%puts @result_reviews%>
<% @result_reviews.each do |review| %>
  <tr>
    <td><%= review.rating %></td>
    <td><%= review.feedback %></td>
    <td><%= Passenger.find(review.passenger_id).name %></td>
    <td><%= Train.find(review.train_id).train_number %></td>
    <td><%= link_to 'Show', review %></td>
    <th> <%= link_to "Edit", edit_review_path(review, :train_id => review.train_id) %></th>
    <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<br>
<br>

  <% if session[:passenger_id] != nil %>
  <%= form_tag(search_review_by_train_number_path, :method => "get") do %>
    <div class="input-group">
      <%= search_field_tag :train_number, params[:train_number], placeholder: "Enter Train Number", class: "form-control" %>
      <div class="input-group-btn">
        <%= button_tag "Search", :class =>'btn btn-info glyphicon glyphicon-search', :auth_name => nil %>
      </div>
    </div>
  <% end %>
  <br>
  <br>
  <%= form_tag(search_review_by_passenger_name_path, :method => "get") do %>
    <div class="input-group">
      <%= search_field_tag :passenger_name, params[:passenger_name], placeholder: "Enter Passenger Name", class: "form-control" %>
      <div class="input-group-btn">
        <%= button_tag "Search", :class =>'btn btn-info glyphicon glyphicon-search', :auth_name => nil %>
      </div>
    </div>
  <% end %>
    <%= link_to "Back to trains", ptrain_show_route_path %>
  <%else%>
    <th><%= link_to 'Back to reviews', review_show_route_path %></th>
  <%end%>
    

app/views/reviews/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @review %>

<div>
  
  <br>
  <%= button_to "Destroy this review", @review, method: :delete %>
  <br>
  
  <% if session[:passenger_id] != nil %>
    <%= link_to "Back to trains", booking_show_route_path %>
  <%else%>
    <th><%= link_to 'Back to reviews', review_show_route_path %></th>
  <%end%>
    
    


</div>